language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops-ptx
  api_key:
    secure: cuMYMz+SZcv9/VmV0AXxBi12O2Xj1kBc4umVVugaa8et5GxkGZqzb0zb5U+sSO4DRvWI4UNhNMFnzkOGuoLFwfSRkT5ylYKDp0OkHP+6NS41Bo3MqsmjXcEc5qNXoACxGC1/0cuzZG6OQ0nI5G8WkM4eQ1DKvamqC6QitzJaYL434Ir+n4p0NU5MBFhDPo/cuF4wj+PyCJo6nsaQLumCf4Q72z/TJWfWeHWJ6sPW6dWSHJdzLzrx//nTJPPHnqZTCWgFTrhEsfIIe8MkT0fEovJj4hCK18tOZw05bcW1pgmD+Lt9vHfiDyGUeJB3GYPLm96TbdEO3Jx45QNIeocgW9rkdKf6UUA82KM1hRgtLK5YaZ634InmOsGeY/8Ev+1qdB1s9/BNsFz+T9Nc+g29PnqMP96EdcjQMri38UC2SMsDkS+7PL+fFNOys++2wv9xLvFipCrf2mpfQ6QKB4gEZv6uAWCaRrvIEVyYCxTqDAR91b/oZx4BFi3hmZsuvsb2rqgN+8ADBk9/TxxhvD37llMLRrJCvFVqj4wa4FhxgRbEgrQppObA9EotFuhwooACQzdpgtg1bupBriEZIZe5cXh97znG8USLur2tpaNNCmTcUx4meVGyD0IZJvM/Sl2MsY9VntcP7FAykmPwfbDQSCcrte7tM/oj/5geNMfQGd8=
